CREATE TABLE `TB_BLOG_RSS` (
  `BLOG_RSS_SEQ` varchar(50) NOT NULL,
  `AUTHOR` varchar(100) NOT NULL,
  `CATEGORY` varchar(100) NOT NULL,
  `TITLE` varchar(2000) NOT NULL,
  `LINK` varchar(300) NOT NULL,
  `DESCRIPTION` varchar(3000) NOT NULL,
  `USE_YN` char(1) NOT NULL,
  `REG_DATE` datetime NOT NULL,
  `UPT_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`BLOG_RSS_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TB_MNGR` (
  `MNGR_SEQ` varchar(50) NOT NULL,
  `ID` varchar(100) NOT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `PASSWORD_KEY` varchar(200) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `USE_YN` char(1) NOT NULL,
  `REG_DATE` datetime DEFAULT NULL,
  `UPT_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MNGR_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TB_RESERVATION` (
  `RESERVATION_SEQ` varchar(50) NOT NULL,
  `RESERVATION_DATE` datetime NOT NULL,
  `RESERVATION_NAME` varchar(100) NOT NULL,
  `PHONE` varchar(13) NOT NULL,
  `CHOOSE_AREA` varchar(1000) NOT NULL,
  `RESERVATION_CONTENT` text DEFAULT NULL,
  `USE_YN` char(1) NOT NULL,
  `REG_DATE` datetime DEFAULT NULL,
  `UPT_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`RESERVATION_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TB_MAINTENANCE_AREA` (
  `MAINTENANCE_AREA_SEQ` varchar(50) NOT NULL,
  `MAINTENANCE_NAME` varchar(100) NOT NULL,
  `REG_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MAINTENANCE_AREA_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;